%%
% The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
% 
% 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
% 
% Let us list the factors of the first seven triangle numbers:
% 
%  1: 1
%  3: 1,3
%  6: 1,2,3,6
% 10: 1,2,5,10
% 15: 1,3,5,15
% 21: 1,3,7,21
% 28: 1,2,4,7,14,28
% We can see that 28 is the first triangle number to have over five divisors.
% 
% What is the value of the first triangle number to have over five hundred divisors?
%%

clearvars;
found = 0;
ii=0;
while ~found
   ii=ii+1;
   % each triangular number can be calc. as n*(n+1)/2
   num = ii*(ii+1)/2;
   k=1:num;
   numDivisors =  length(k(rem(num,k)==0));
   if(numDivisors>500)
       found = 1;
   end
end

result = num