%%
% Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
% 
% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
% 
% By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
%%

fibb(1) = 1;
fibb(2) = 2;
%generate fibbonaci sequence
while fibb(end)<4e6
   fibb(end+1) = fibb(end)+fibb(end-1); 
end
%get rid of last element as it is greater than 4e6
fibb = fibb(1:end-1);

result = sum(fibb(mod(fibb,2)==0))
%result = 4613732